version: '3.7'

services:

  nginx:
    image: nginx:1.14.0
    depends_on:
      - fpm
    ports:
      - 8006:80
    volumes:
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf

  fpm:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www/html

volumes:
  app:
